plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - .git/**/*
    - gemfiles/**/*
    - test/rails_app/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*

Layout/LineLength:
  Exclude:
    - 'Rakefile'

Metrics/AbcSize:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
