require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
