AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Lint/UselessAssignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
