AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Lint/UselessAssignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Metrics:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  AllowComments: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false
